version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fgmember/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../source:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 3100:80
    volumes:
      - ../source:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
    networks:
      - app-network        
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: UcpWJ4gQE8qCVSyD
      MYSQL_DATABASE: memberdb
      MYSQL_USER: muser
      MYSQL_PASSWORD: qKqcxptGgadvsvcK
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local